apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-cronjob
spec:
  schedule: "15 18 * * *" # Runs at 6:15 PM every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-request
              image: curlimages/curl:latest # Lightweight curl image
              args:
                - /bin/sh
                - -c
                - "curl -X GET https://your-api-endpoint.com/healthcheck"
          restartPolicy: OnFailure