apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: java-app
spec:
  template:
    metadata:
      annotations:
        # Pre-warming configurations
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/target: "5"
    spec:
      containers:
        - image: docker.io/akshit2405/java-knative-app:v1
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "Knative Java App"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"